name: Build image for Production
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy with IAC to AWS EC2 and Redshift Resources
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout Files
        uses: actions/checkout@v2
      - run: |
          if ! which aws > /dev/null 2>&1; then
            echo "install aws cli"
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            aws --version
          fi
          if ! which sam > /dev/null 2>&1; then
            sudo ./sam-installation/install
            sam --version
          fi

# https://aws.amazon.com/premiumsupport/knowledge-center/rds-connectivity-instance-subnet-vpc/
# https://aws.amazon.com/premiumsupport/knowledge-center/rds-connectivity-instance-subnet-vpc/